#!/usr/bin/env bash

zero_sha=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

read local_ref local_sha remote_ref remote_sha

## check if any changes
if [[ -z $local_ref ]]; then
    exit 0
fi

## check if delete branch
if test "$local_sha" = "$zero_sha"; then
    exit 0
fi

## read config
if ! [[ -z $VAR_GIT_HOOKS_TEMPLATES_PATH ]]; then
    source ${VAR_GIT_HOOKS_TEMPLATES_PATH}Git.Hooks/global/config.sh
fi

source ../Git.Hooks/global/config.sh
source .githooks/config.sh

## check uncommitted files
if [[ ( -z $VAR_CHECK_UNCOMMITTED_FILES || $VAR_CHECK_UNCOMMITTED_FILES = true ) && $(git status --porcelain) ]]; then
    echo -e "${COLOR_RED}Uncommitted files present. Aborting push.${COLOR_NO}"
    exit 1
fi