#!/usr/bin/env bash

# terraform
VAR_TERRAFORM_DEFAULT_ROOT_FOLDER_PATHS=".terraform"
VAR_TERRAFORM_ROOT_FOLDER_PATHS=$VAR_TERRAFORM_DEFAULT_ROOT_FOLDER_PATHS
VAR_TERRAFORM_ENV_FOLDER_PATHS=("dev" "test" "prod")

if ! [[ -z $VAR_PROJECT_NAME ]]; then
    VAR_TERRAFORM_ROOT_FOLDER_PATHS="$VAR_TERRAFORM_DEFAULT_ROOT_FOLDER_PATHS/$VAR_PROJECT_NAME"
fi