#!/usr/bin/env bash

## read terraform config
if ! [[ -z $VAR_GIT_HOOKS_TEMPLATES_PATH || $VAR_GIT_HOOKS_TEMPLATES_PATH = $VAR_GIT_HOOKS_TEMPLATES_DEFAULT_PATH ]]; then
    source ${VAR_GIT_HOOKS_TEMPLATES_PATH}Git.Hooks/terraform/config.sh
fi

source ../Git.Hooks/terraform/config.sh
source .githooks/terraform/config.sh

## check if terraform folder has changes
git diff --name-only --quiet -- ".terraform/*"

if [[ $? = 0 ]]; then
    return
fi

## terraform recursive format check
( cd .terraform && terraform fmt -check -recursive $VAR_TERRAFORM_OUTPUT_NO_COLOR )

if [[ $? -ne 0 ]]; then
    echo -e "${COLOR_RED}Invalid terraform format. Aborting push.${COLOR_NO}"
    exit 1
fi

## terraform validate envs
for folderPath in ${VAR_TERRAFORM_ENV_FOLDER_PATHS[@]}; do
    ( cd .terraform/$folderPath && terraform init -backend=false $VAR_TERRAFORM_OUTPUT_NO_COLOR && terraform validate $VAR_TERRAFORM_OUTPUT_NO_COLOR )

    if [[ $? -ne 0 ]]; then
        echo -e "${COLOR_RED}Terraform not valid '.terraform/$folderPath'. Aborting push.${COLOR_NO}"
        exit 1
    fi
done